SIZE = WIDTH, HEIGHT = 1280, 720

CASE_SIZE = 80

NB_ELEM_X = WIDTH // CASE_SIZE
NB_ELEM_Y = HEIGHT // CASE_SIZE

POS_TOUR_1 = (5 * CASE_SIZE, 2 * CASE_SIZE)
POS_TOUR_2 = (10 * CASE_SIZE, 2 * CASE_SIZE)
POS_TOUR_3 = (10 * CASE_SIZE, 6 * CASE_SIZE)
POS_TOUR_4 = (5 * CASE_SIZE, 6 * CASE_SIZE)

FPS = 60

TOURS = [POS_TOUR_1, POS_TOUR_2, POS_TOUR_3, POS_TOUR_4]
FRIES_SPEED = 6
