import pygame

COLLECT_POTATOE = pygame.USEREVENT + 10
DEAD_ZOMBIE = pygame.USEREVENT + 11
FEEDED = pygame.USEREVENT + 12
OUT_OF_FOOD = pygame.USEREVENT + 13
DIG = pygame.USEREVENT + 14
PLAYER_DEAD_EVENT = pygame.USEREVENT + 15
DAMAGED_ZOMBIE = pygame.USEREVENT + 16


DAMAGE_EVENT = pygame.USEREVENT + 20
CHANGE_NIGHT = pygame.USEREVENT + 21
